import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import {
  AGENT_LABEL,
  IS_WINDOWS,
  NODE_CANDIDATES,
  PATHS,
  copyTree,
  ensureHome,
  execFileAsync,
  windowsPaths,
} from './util.mjs';
import { sleep } from './util.mjs';

const UID = typeof process.getuid === 'function' ? process.getuid() : 501;

const WRAPPER_MARKER = '# generated by typeless-auto-update-block';

/** Shell wrapper that resolves node at runtime, so a moved/upgraded node still works. */
export function wrapperScript(platform = process.platform) {
  if (platform === 'win32') {
    return `@echo off\r
rem ${WRAPPER_MARKER} - resolves node at runtime\r
setlocal\r
set "NODE_BIN="\r
for %%P in ("%ProgramFiles%\\nodejs\\node.exe" "%ProgramFiles(x86)%\\nodejs\\node.exe" "%LOCALAPPDATA%\\Programs\\nodejs\\node.exe" "%APPDATA%\\nvm\\node.exe") do (\r
  if not defined NODE_BIN if exist %%P set "NODE_BIN=%%~P"\r
)\r
if not defined NODE_BIN for /f "delims=" %%P in ('where node 2^>nul') do if not defined NODE_BIN set "NODE_BIN=%%P"\r
if not defined NODE_BIN (\r
  echo typeless-auto-update-block: node.exe not found 1>&2\r
  exit /b 1\r
)\r
"%NODE_BIN%" "%LOCALAPPDATA%\\typeless-auto-update-block\\app\\src\\cli.mjs" serve --foreground\r
`;
  }
  const candidates = NODE_CANDIDATES.join(' ');
  return `#!/bin/sh
${WRAPPER_MARKER} - resolves node at runtime
NODE_BIN=""
for candidate in \${UPDATE_FREEZE_NODE:-} ${candidates}; do
  if [ -n "$candidate" ] && [ -x "$candidate" ]; then NODE_BIN="$candidate"; break; fi
done
if [ -z "$NODE_BIN" ]; then NODE_BIN="$(command -v node 2>/dev/null || true)"; fi
if [ -z "$NODE_BIN" ]; then
  for candidate in "$HOME"/.nvm/versions/node/*/bin/node "$HOME"/.volta/bin/node "$HOME"/.local/share/fnm/node-versions/*/installation/bin/node /opt/homebrew/opt/node*/bin/node; do
    if [ -x "$candidate" ]; then NODE_BIN="$candidate"; break; fi
  done
fi
if [ -z "$NODE_BIN" ]; then
  echo "typeless-auto-update-block: node not found in PATH or common locations" >&2
  exit 1
fi
exec "$NODE_BIN" "$HOME/.typeless-auto-update-block/app/src/cli.mjs" serve --foreground
`;
}

export function agentPlistXml({ logPath = PATHS.log }) {
  const args = ['/bin/sh', PATHS.wrapper];
  const argsXml = args.map((arg) => `    <string>${escapeXml(arg)}</string>`).join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>
  <string>${AGENT_LABEL}</string>
  <key>ProgramArguments</key>
  <array>
${argsXml}
  </array>
  <key>RunAtLoad</key>
  <true/>
  <key>KeepAlive</key>
  <dict>
    <key>SuccessfulExit</key>
    <false/>
  </dict>
  <key>ThrottleInterval</key>
  <integer>10</integer>
  <key>ProcessType</key>
  <string>Background</string>
  <key>StandardOutPath</key>
  <string>${escapeXml(logPath)}</string>
  <key>StandardErrorPath</key>
  <string>${escapeXml(logPath)}</string>
  <key>EnvironmentVariables</key>
  <dict>
    <key>PATH</key>
    <string>/usr/bin:/bin:/usr/sbin:/sbin:/opt/homebrew/bin:/usr/local/bin</string>
  </dict>
</dict>
</plist>
`;
}

function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

async function launchctl(args) {
  return execFileAsync('/bin/launchctl', args, { timeout: 15000 });
}

export async function agentLoaded() {
  if (IS_WINDOWS) {
    try {
      const { stdout } = await execFileAsync(
        'reg',
        ['query', windowsPaths().runKey, '/v', 'typeless-auto-update-block'],
        { timeout: 10000 },
      );
      return stdout.includes('typeless-auto-update-block');
    } catch {
      return false;
    }
  }
  try {
    await launchctl(['print', `gui/${UID}/${AGENT_LABEL}`]);
    return true;
  } catch {
    return false;
  }
}

/** Copy the tool to ~/.typeless-auto-update-block/app so the repository can be moved or deleted. */
export function installToolCopy(cliPath) {
  ensureHome();
  const sourceRoot = path.resolve(path.dirname(cliPath), '..');
  if (path.resolve(PATHS.installRoot) === path.resolve(sourceRoot)) {
    return { copied: false, installRoot: PATHS.installRoot };
  }
  copyTree(path.join(sourceRoot, 'src'), path.join(PATHS.installRoot, 'src'));
  for (const file of ['package.json', 'README.md', 'LICENSE']) {
    const from = path.join(sourceRoot, file);
    if (fs.existsSync(from)) fs.copyFileSync(from, path.join(PATHS.installRoot, file));
  }
  return { copied: true, installRoot: PATHS.installRoot };
}

export function writeWrapper() {
  ensureHome();
  fs.mkdirSync(PATHS.binDir, { recursive: true, mode: 0o700 });
  const script = wrapperScript();
  fs.writeFileSync(PATHS.wrapper, script, { mode: 0o755 });
  if (!IS_WINDOWS) fs.chmodSync(PATHS.wrapper, 0o755);
  return PATHS.wrapper;
}

export async function installAgent({ cliPath, start = true } = {}) {
  if (!cliPath) throw new Error('cliPath is required to install the agent');
  const copy = installToolCopy(cliPath);
  const wrapper = writeWrapper();
  if (IS_WINDOWS) {
    const { runKey } = windowsPaths();
    await execFileAsync('reg', [
      'add',
      runKey,
      '/v',
      'typeless-auto-update-block',
      '/t',
      'REG_SZ',
      '/d',
      `"${wrapper}"`,
      '/f',
    ], { timeout: 10000 });
    if (start) {
      const child = execFileAsync('cmd', ['/c', 'start', '""', '/b', wrapper], { timeout: 5000 });
      child.catch(() => {});
    }
    return { changed: true, platform: 'windows', wrapper, runKey, ...copy };
  }
  fs.mkdirSync(path.dirname(PATHS.plist), { recursive: true });
  const xml = agentPlistXml({});
  const previous = fs.existsSync(PATHS.plist) ? fs.readFileSync(PATHS.plist, 'utf8') : null;
  if (previous === xml && (await agentLoaded())) {
    return { changed: false, plist: PATHS.plist, wrapper, ...copy };
  }
  if (await agentLoaded()) {
    await uninstallAgent().catch(() => {});
    // bootout is asynchronous: wait until launchd really forgot the job
    for (let attempt = 0; attempt < 10 && (await agentLoaded()); attempt += 1) {
      await sleep(300);
    }
  }
  fs.writeFileSync(PATHS.plist, xml, { mode: 0o644 });
  let lastError = null;
  for (let attempt = 0; attempt < 3; attempt += 1) {
    try {
      await launchctl(['bootstrap', `gui/${UID}`, PATHS.plist]);
      lastError = null;
      break;
    } catch (error) {
      lastError = error;
      await sleep(500);
    }
  }
  if (lastError) {
    try {
      await launchctl(['load', '-w', PATHS.plist]);
      lastError = null;
    } catch (fallbackError) {
      throw new Error(`could not load launch agent: ${fallbackError.message || lastError.message}`);
    }
  }
  for (let attempt = 0; attempt < 10 && !(await agentLoaded()); attempt += 1) {
    await sleep(300);
  }
  if (!(await agentLoaded())) {
    throw new Error(`launch agent ${AGENT_LABEL} did not stay loaded after install`);
  }
  return { changed: true, plist: PATHS.plist, wrapper, ...copy };
}

export async function uninstallAgent() {
  if (IS_WINDOWS) {
    let changed = false;
    try {
      await execFileAsync('reg', ['delete', windowsPaths().runKey, '/v', 'typeless-auto-update-block', '/f'], {
        timeout: 10000,
      });
      changed = true;
    } catch {
      // not registered
    }
    return { changed, runKey: windowsPaths().runKey };
  }
  let changed = false;
  try {
    await launchctl(['bootout', `gui/${UID}/${AGENT_LABEL}`]);
    changed = true;
  } catch {
    try {
      await launchctl(['unload', '-w', PATHS.plist]);
      changed = true;
    } catch {
      // not loaded
    }
  }
  if (fs.existsSync(PATHS.plist)) {
    fs.unlinkSync(PATHS.plist);
    changed = true;
  }
  return { changed, plist: PATHS.plist };
}
